#!/bin/env bash 
#===============================================================================
#
#          FILE: glhckcht
# 
#         USAGE: ./glhckcht sl pref
# 
#   DESCRIPTION: Saves or loads glhack save state.
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Yordan Radunchev (), yordan@radunchev.com
#  ORGANIZATION: 
#       CREATED: 2017-02-25 19:56
#      REVISION: 001
#          TODO: Option to list available saved states
#===============================================================================

#!USER CONFIGURATION #modify this as you need
glhack_save_dir=/var/games/glhack/save #where saves are originally
glhack_state_dir=${HOME}/.glhack_save #where you want to save the saves
#!/USER CONFIGURATION

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'USAGE glhckcht sl pref

SUMMARY

  Saves or loads glhack save state.

DESCRIPTION

  You must save before in glhack for this to work.

  You cannot use this script while glhack is running: glhack must be off for saving and loading!!!

  Output save dir is created automatically each time the script is run.

INSTALLATION

  Nethack dir, output save dir must and save separtor must be specified by
  modifying the variables sep, glhack_save_dir and glhack_state_dir at the beginning
  of the source code of this script.

  If you do this after saving, old saves will be lost.

SAMPLE CALLS

  #first save glhack with S command.
  #while the game is quit use:

  glhckcht s 1; glhack    #saves state 1, and comes back to the game
  glhckckt s "hard part"; glhack   #saves state "hard part"

  #to load a state, quit with #quit
  #while the game is quit do:

  glhckcht l 1; glhack    # loads state 1, and comes back to the game
  glhckcht l "hard part"; glhack    # loads state "hard part"

  #when you start the game it should be back at last place.
  #TIP: hit up on the terminal to access terminal history after loading and saving to quickly load and save.

AUTHORS

  Yordan Radunchev 
  based on initial work of Ciro D. Santilli (https://github.com/cirosantilli/bash-cheat)
  ' 1>&2
}

if [ $# -ne 2 ]; then
  usage
fi

sl=${1}
pref=${2}
sep="_" #separator for the new save name. cannot appear on the prefix you give!!
curuser=$USER

#check no separator SEP in prefix
if [[ ${pref} != ${sep} && ${pref} == *${sep}* ]]; then
  echo "State name cannot contain \"${sep}\". Use another state name."
fi

[[ ! -d ${glhack_state_dir} ]] && mkdir -p ${glhack_state_dir}

if [ ${sl} == s ]; then
  for f in ${glhack_save_dir}/*; do
      bname="$(basename ${f})"
      echo ${f}
      sudo cp -f ${f} ${glhack_state_dir}/${pref}${sep}${bname}
      sudo cp -f ${f} ${glhack_state_dir}/${sep}${sep}${bname} #also saves to a separator
      break
  done
elif [ ${sl} == l ]; then
  for f in ${glhack_state_dir}/${pref}*; do
    bname="$(basename ${f})"
    bname_old="${bname##*${sep}}"
    sudo cp -f ${f} ${glhack_save_dir}/${bname_old}
    sudo chown ${curuser}:games ${glhack_save_dir}/${bname_old}

    break
  done
fi

exit 0

